<?php
$this->title = 'Удалить группу';
$this->headTitle($this->title);

if($this->notEmpty === true) {
    $this->customersFilterURL = $this->escape($this->url(array('controller'=>'customers', 'action'=>'index', 'filterByID'=>$this->group['id'])));
    $this->customerSingular = 'Он также будет удален из базы.';
    $this->customerPlural = 'Они также будут удалены из базы.';
    $this->chosenCustomerForm = $this->memberCount > 1 ? $this->customerPlural : $this->customerSingular;
    $this->notEmptyMessage = "<p style='text-align:center;'>В этой группе находится <a href='$this->customersFilterURL' style='color:inherit; text-decoration: underline;'><strong>$this->memberCount $this->nounForm</strong></a>. $this->chosenCustomerForm</p>";
}
?>

<p style="text-align:center;">Вы уверены, что хотите удалить группу "<strong><?php echo $this->escape($this->group['name']); ?></strong>"?</p>
<?php if ($this->notEmpty === true){echo $this->notEmptyMessage; }; ?>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" style="text-align: center;" method="POST">
    <div>
          <input type="hidden" name="id" value="<?php echo $this->group['id']; ?>" />
          <input class="btn" type="submit" name="del" value="Да" />
          <input class="btn" type="submit" name="del" value="Нет" />
    </div>
</form>