<?php
$this->title = "Группы";
$this->headTitle($this->title);
?>
<table id='groupsTable'>
    <tr class='tableData'>
        <th>
            <a title='Сортировать по ID' href='<?php echo $this->url(array('o'=>$this->orderLinks['id'][0])) ?>'>
                Код <i class="<?php echo $this->escape($this->orderLinks['id'][1]) ?>"></i>
            </a>
        </th>
        <th>
            <a title='Сортировать по названию' href='<?php echo $this->url(array('o'=>$this->orderLinks['name'][0])) ?>'>
                Название <i class="<?php echo $this->escape($this->orderLinks['name'][1]) ?>"></i>
            </a>
        </th>
        <th>
            <a title='Сортировать по количеству участников' href='<?php echo $this->url(array('o'=>$this->orderLinks['memberCount'][0])) ?>'>
                Абонентов <i class="<?php echo $this->escape($this->orderLinks['memberCount'][1]) ?>"></i>
            </a>
        </th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->groups as $group) : ?>
    <tr>
        <td><?php echo $this->escape($group->id);?></td>
        <td><?php echo $this->escape($group->name);?></td>
        <td><?php echo $this->escape($group->memberCount);?></td>
        <td class='listActions'>
            <a title='Изменить' href="<?php echo $this->url(array('controller'=>'groups', 'action'=>'edit', 'id'=>$group->id));?>">
                <i class='icon-cog'></i>
            </a>
            <a title='Удалить' href="<?php echo $this->url(array('controller'=>'groups', 'action'=>'delete', 'id'=>$group->id));?>">
                <i class='icon-remove'></i>
            </a>
        </td>
    <?php endforeach; ?>
</table>
<br />
<?php echo $this->paginationControl($this->groups, 'Sliding', 'paginator.phtml'); ?>