<?php
$this->title = "Пользователи";
$this->headTitle($this->title);
?>
<div class="btn-group expiration-filter-dropdown">
    <button class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
        <i class="icon-filter"></i> По дате <i class="caret"></i>
    </button>
    <ul class="dropdown-menu">
        <li>
            <a href="<?php echo $this->url(array('expiration'=>'expired')); ?>">
                Просроченные
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('expiration'=>'not-expired')); ?>">
                Непросроченные
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="/customers/">Все</a>
        </li>
    </ul>
</div>

<div class="btn-group groups-dropdown-filter">
    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        <i class="icon-filter"></i> По группам <i class="caret"></i>
    </button>
    <ul class="dropdown-menu">
        <?php foreach($this->groups as $group): ?>
        <li>
            <a href="<?php echo $this->url(array('filterByID'=>$group['id'])); ?>">
                <?php echo $this->escape($group['name']); ?>
            </a>
        </li>
        <?php endforeach; ?>
        <li class="divider"></li>
        <li>
            <a href="/customers/">Все</a>
        </li>
    </ul>
</div>

<?php if(count($this->customers) > 0): ?>
    <table id='resultsTable'>
        <tr class='tableData'>
            <th>
                <a title='Сортировать по ID' href='<?php echo $this->url(array('o'=>$this->orderLinks['id'][0])) ?>'>
                    ID <i class="<?php echo $this->escape($this->orderLinks['id'][1]) ?>"></i>
                </a>
            </th>
            <th>
                <a title='Сортировать по логину' href='<?php echo $this->url(array('o'=>$this->orderLinks['login'][0])) ?>'>
                    Логин <i class="<?php echo $this->escape($this->orderLinks['login'][1]) ?>"></i>
                </a>
            </th>
            <th>
                <a title='Сортировать по e-mail' href='<?php echo $this->url(array('o'=>$this->orderLinks['email'][0])) ?>'>
                    E-mail <i class="<?php echo $this->escape($this->orderLinks['email'][1]) ?>"></i>
                </a>
            </th>
            <th>
                <a title='Сортировать по названию группы' href='<?php echo $this->url(array('o'=>$this->orderLinks['group'][0])) ?>'>
                    Группа <i class="<?php echo $this->escape($this->orderLinks['group'][1]) ?>"></i>
                </a>
            </th>
            <th>
                <a title='Сортировать по дате просрочки' href='<?php echo $this->url(array('o'=>$this->orderLinks['exp_date'][0])) ?>'>
                    Активен до <i class="<?php echo $this->escape($this->orderLinks['exp_date'][1]) ?>"></i>
                </a>
            </th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach($this->customers as $customer) : ?>
        <tr>
            <td><?php echo $this->escape($customer->id);?></td>
            <td><?php echo $this->escape($customer->login);?></td>
            <td><?php echo $this->escape($customer->email);?></td>
            <td><?php echo $this->escape($customer->group_name);?></td>
            <td><?php echo $this->escape($customer->acc_exp_date);?></td>
            <td class='listActions'>
                <a title='Изменить' href="<?php echo $this->url(array('action'=>'edit', 'id'=>$customer->id));?>">
                    <i class='icon-cog'></i>
                </a>
                <a title='Удалить' href="<?php echo $this->url(array('action'=>'delete', 'id'=>$customer->id));?>">
                    <i class='icon-remove'></i>
                </a>
            </td>
        </tr>

        <?php endforeach; ?>
    </table>
    <br />
    <?php echo $this->paginationControl($this->customers, 'Sliding', 'paginator.phtml'); ?>
<?php else: ?>
    <br />
    <br />
    <h1 style="text-align: center; font-size: 16pt;">Извините, но по этим условиям ничего нет :(</h1>
    <h1 style="text-align: center; font-size: 16pt; text-decoration: underline;"><a href="/customers/">Огласить весь список</a>? </h1>
<?php endif; ?>