<form id="login" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
    <div class="control-group">
        <label class="control-label" for="username">Логин</label>
        <div class="controls">
            <?php echo $this->element->username; ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="password">Пароль</label>
        <div class="controls">
            <?php echo $this->element->password; ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->submit; ?>
        </div>
    </div>
</form>