<?php
$this->headTitle()->setSeparator(' | ');
$this->headTitle('Cybertone test');
echo $this->doctype() . "\n";
?>
<html>
    <head>
        <?php echo $this->headMeta() . "\n"; ?>
        <?php echo $this->headTitle() . "\n"; ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css') . "\n"; ?>
        <?php
        echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/font-awesome.css') . "\n";
        echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap.css') . "\n";
        echo $this->headLink()->prependStylesheet('http://fonts.googleapis.com/css?family=Source+Code+Pro&subset=latin-ext') . "\n";
        echo $this->headScript()->prependFile('http://code.jquery.com/jquery-2.0.0.min.js');
        echo $this->headScript()->prependFile($this->baseUrl() . '/js/bootstrap.min.js');
        ?>
    </head>
    <body>
        <style type="text/css">
            /* Committing the cardinal sin of web design :) */
            form, dt {
                width: auto;
                float: none;
            }
        </style>
        <div id="content">
            <h1><?php echo $this->escape($this->title); ?></h1>
            <br />
            <br />
            <?php echo $this->layout()->content . "\n"; ?>
        </div>
    </body>
</html>