<?php
$this->headTitle()->setSeparator(' | ');
$this->headTitle('UserBase');
$homeLink = $this->url(array('controller'=>'index', 'action'=>'index'));
$customersIndexLink = $this->url(array('controller'=>'customers', 'action'=>'index'));
$customersAddLink = $this->url(array('controller'=>'customers', 'action'=>'add'));
$groupsIndexLink = $this->url(array('controller'=>'groups', 'action'=>'index'));
$groupsAddLink = $this->url(array('controller'=>'groups', 'action'=>'add'));
echo $this->doctype() . "\n";

$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) { $this->loggedIn = true; }

?>
<html>
    <head>
        <?php
        echo $this->headMeta() . "\n";
        echo $this->headTitle() . "\n";
        echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css') . "\n";
        echo $this->headLink()->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.min.css') . "\n";
        echo $this->headLink()->prependStylesheet('http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css') . "\n";
        echo $this->headLink()->prependStylesheet('http://fonts.googleapis.com/css?family=Source+Code+Pro&subset=latin-ext') . "\n";
        ?>
    </head>
    <body>

        <div id="content">
            <div class="navbar navbar-static-top" style="margin: -1px -1px 0; padding-bottom: 25px;">
                <div class="navbar-inner">
                    <div class="container" style="width: auto; padding: 0 20px;">
                        <a class="brand" href="/">UserBase</a>
                        <ul class="nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Пользователи <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url(array('controller'=>'customers', 'action'=>'index')); ?>">Посмотреть</a></li>
                                    <li><a href="<?php echo $this->url(array('controller'=>'customers', 'action'=>'add')); ?>">Добавить</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Группы <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url(array('controller'=>'groups', 'action'=>'index')); ?>" class="dropdown-toggle">Посмотреть</a></li>
                                    <li><a href="<?php echo $this->url(array('controller'=>'groups', 'action'=>'add')); ?>">Добавить</a></li>
                                </ul>
                            </li>
                            <?php if ($this->loggedIn) : ?>
                                <li><a href="<?php echo $this->url(array('controller'=>'auth', 'action'=>'logout')); ?>">Выйти</a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
            <h1><?php echo $this->escape($this->title); ?></h1>
            <br />
            <?php if (count($this->messages)) : ?>
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo $this->escape($this->messages[0]); ?>
                </div>
            <?php
                endif;
                echo $this->layout()->content . "\n";
            ?>
        </div>
        <script src="http://code.jquery.com/jquery-2.0.1.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl() . '/js/main.js'; ?>"></script>
    </body>
</html>